name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  cached_network_image: ^3.2.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_inappwebview: ^5.7.2+3
  flutter_localizations:
    sdk: flutter
  go_router: ^7.0.1
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.8.0

  

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
 

flutter:
  uses-material-design: true
  generate: true
